### PR TITLE
Improve test coverage on [mds-daily]

### PR DESCRIPTION
**Pull request by macsj200**
*DRAFT* Don't merge yet

Refactor + improve tests

I moved a bunch of stuff around, so we should probably
also write some Cypress tests for this to make sure
we don't break anything.

## PR Checklist

 - [ X] simple searchable title - `[mds-db] Add PG env var`, `[config] Fix eslint config`
 - [X ] briefly describe the changes in this PR
 - [x] mark as draft if should not be merged
 - [ ] write tests for all new functionality

## Impacts
- [ ] Provider
- [ ] Agency
- [ ] Audit
- [ ] Policy
- [ ] Compliance
- [ X] Daily
- [ ] Native
- [ ] Policy Author

### CODE REVIEW

**Comment by macsj200** [comment]
This got out of hand pretty quickly. There's still some work I want to do, but I want a sanity check before I dive deeper.

**Comment by wesleyfsmith** [comment]
Pretty huge delta haha

**Comment by wesleyfsmith** [comment]
I approve the breaking out into multiple files, I think it's already a lot easier to grok.

**Comment by mdurling** [comment]
Only 7 other APIs needing similar treatment to go. 😀

**Pull request merged**
